#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP-0 -d I III IV V VI VIII IX X
bspc monitor DVI-D-0 -d II VII
# bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

setxkbmap br &
nitrogen --restore &

picom & 

# xrandr --output DVI-D-0 --mode 1920x1080 --rate 60 --pos 0x0 --rotate left --output HDMI-0 --off --output HDMI-1 --off --output DP-0 --primary --mode 1920x1080 --rate 144 --pos 1080x420 --rotate normal --output DP-1 --off --output DP-2 --off --output DP-3 --off &

# nvidia-settings --assign CurrentMetaMode="DP-0: 1920x1080_144 +1080+420 {ForceCompositionPipeline=On, ForceFullCompositionPipeline=On}, DVI-D-0: nvidia-auto-select +0+0 {rotation=left}"

nvidia-settings --load-config-only &

polybar &
