set-option -g prefix C-t
bind -r k select-pane -U 
bind -r j select-pane -D 
bind -r h select-pane -L 
bind -r l select-pane -R
bind % split-window -h -c "#{pane_current_path}"

set -g mouse on

# tmux display things in 256 colors
set-option -g default-terminal "screen-256color"
set-option -g terminal-overrides "screen-256color"
set -g default-terminal "xterm-256color"
set -ga terminal-overrides ",xterm-256color:Tc"

